version: 0.1
component: build
timeoutInSeconds: 20000
runAs: root
shell: bash
env:
  exportedVariables:
   - GITHUB_MD5_HASH
   - GITLAB_MD5_HASH
   - BITBUCKET_CLOUD_MD5_HASH
   - BITBUCKET_SERVER_MD5_HASH
   - PUBLIC_GITLAB_SERVER_MD5_HASH
   - VBS_MD5_HASH
   - SCM_MD5_HASH
steps:
  - type: Command
    name: "Calculating MD5 Hash of Github Large Repo"
    command: |
      cd ${OCI_WORKSPACE_DIR}
      zip -dq TestBuildSource_GitHub.zip */.git/*
      export GITHUB_MD5_HASH=`md5sum TestBuildSource_GitHub.zip | awk '{ print $1 }'`
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of Github Large Repo failed :("
  - type: Command
    name: "Calculating MD5 Hash of Gitlab Large Repo"
    command: |
      cd ${OCI_WORKSPACE_DIR}
      zip -dq TestBuildSource_GitLab.zip */.git/*
      export GITLAB_MD5_HASH=`md5sum TestBuildSource_GitLab.zip | awk '{ print $1 }'`
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of Gitlab Large Repo failed :("
  - type: Command
    name: "Calculating MD5 Hash of Bitbucket Cloud Large Repo"
    command: |
      cd ${OCI_WORKSPACE_DIR}
      zip -dq TestBuildSource_BitbucketCloud.zip */.git/*
      export BITBUCKET_CLOUD_MD5_HASH=`md5sum TestBuildSource_BitbucketCloud.zip | awk '{ print $1 }'`
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of Bitbucket Cloud Large Repo failed :("
  - type: Command
    name: "Calculating MD5 Hash of Bitbucket Server Large Repo"
    command: |
      cd ${OCI_WORKSPACE_DIR}
      zip -dq TestBuildSource_BitbucketServer.zip */.git/*
      export BITBUCKET_SERVER_MD5_HASH=`md5sum TestBuildSource_BitbucketServer.zip | awk '{ print $1 }'`
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of Bitbucket Server Large Repo failed :("
  - type: Command
    name: "Calculating MD5 Hash of Public Gitlab Server Large Repo"
    command: |
      cd ${OCI_WORKSPACE_DIR}
      zip -dq TestBuildSource_PublicGitlabServer.zip */.git/*
      export PUBLIC_GITLAB_SERVER_MD5_HASH=`md5sum TestBuildSource_PublicGitlabServer.zip | awk '{ print $1 }'`
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of Public Gitlab Server Large Repo failed :("
  - type: Command
    name: "Calculating MD5 Hash of VBS Large Repo"
    command: |
      cd ${OCI_WORKSPACE_DIR}
      zip -dq TestBuildSource_Vbs.zip */.git/*
      export VBS_MD5_HASH=`md5sum TestBuildSource_Vbs.zip | awk '{ print $1 }'`
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of VBS Large Repo failed :("
  - type: Command
    name: "Calculating MD5 Hash of SCM Large Repo"
    command: |
      cd ${OCI_WORKSPACE_DIR}
      zip -dq TestBuildSource_Scm.zip */.git/*
      export SCM_MD5_HASH=`md5sum TestBuildSource_Scm.zip | awk '{ print $1 }'`
    onFailure:
      - type: Command
        command: |
          echo "Calculating MD5 Hash of SCM Large Repo failed :("
  - type: Command
    name: "Building spark (Github Large Repo)"
    command: |
      chmod -R +x ./build/mvn
      ./build/mvn -DskipTests clean package
  - type: Command
    name: "Run the Pi example locally"
    command: |
      chmod -R +x .
      ./bin/run-example SparkPi