# IMPORTANT : In case there are any changes made to this repo, please update the expected MD5 hash in the below file
# https://bitbucket.oci.oraclecorp.com/projects/DLCBLD/repos/dlc-build-service/browse/dlc-build-service-canary/src/main/java/com/oracle/pic/dlc/build/integtest/usecase/longrunning/BldLargeRepoUseCaseTest.java
version: 0.1
component: build
timeoutInSeconds: 20000
runAs: root
shell: bash
env:
  exportedVariables:
   - version
steps:

  - type: Command
    name: "building spark in local"
    command: |
      chmod -R +x ./build/mvn
      ./build/mvn -DskipTests clean package
#   - type: Command
#     name: "Running tests"
#     command: |
#       ./dev/run-tests
  - type: Command
    name: "run the Pi example locally"
    command: |
      chmod -R +x .
      ./bin/run-example SparkPi      
